import { prisma } from '@/lib/db'
import type { TrendCategory } from './types'

/**
 * Maps agent domains to the trend categories they should react to.
 */
const DOMAIN_CATEGORY_MAP: Record<string, TrendCategory[]> = {
  // Original agents
  stoic: ['tech', 'culture', 'general', 'philosophy', 'business'],
  mindfulness: ['health', 'culture', 'general', 'philosophy', 'relationships'],
  futurism: ['tech', 'science', 'general', 'business'],
  business: ['finance', 'business', 'tech', 'politics'],
  // Comedy
  comedy_roast: ['culture', 'entertainment', 'tech', 'politics', 'general'],
  comedy_memes: ['culture', 'entertainment', 'tech', 'general', 'comedy'],
  // Finance
  finance_crypto: ['finance', 'business', 'tech', 'politics'],
  finance_personal: ['finance', 'business', 'general'],
  // Health & Fitness
  fitness_gym: ['fitness', 'health', 'science', 'general'],
  health_mental: ['health', 'culture', 'relationships', 'general'],
  // Tech
  tech_coding: ['tech', 'science', 'education'],
  science_general: ['science', 'tech', 'health', 'general'],
  // Entertainment
  culture_movies: ['entertainment', 'culture', 'general'],
  culture_music: ['entertainment', 'culture', 'general'],
  // Motivation
  motivation_hustle: ['business', 'tech', 'culture', 'general'],
  // Relationships
  relationships_dating: ['relationships', 'culture', 'entertainment', 'general'],
  // Food
  food_recipes: ['food', 'health', 'culture', 'general'],
  // Entertainment (creative)
  entertainment_stories: ['culture', 'entertainment', 'science', 'general'],
  entertainment_trivia: ['science', 'entertainment', 'culture', 'general', 'tech'],
  // Education
  education_history: ['culture', 'politics', 'general', 'entertainment', 'science'],
  education_languages: ['culture', 'education', 'entertainment', 'general'],
  education_math: ['science', 'tech', 'education', 'finance', 'general'],
}

/**
 * Find trending topics relevant to a specific agent.
 * Returns active trends matching the agent's domain categories
 * that haven't already been used by this agent.
 */
export async function matchTrendsToAgent(
  agentId: string,
  domain: string,
  limit: number = 3
): Promise<
  {
    id: string
    title: string
    description: string | null
    category: string
    viralityScore: number
  }[]
> {
  const categories = DOMAIN_CATEGORY_MAP[domain]
  if (!categories || categories.length === 0) return []

  // Get trends already generated by this agent
  const usedTrendIds = await prisma.agentTrend.findMany({
    where: {
      agentId,
      status: 'generated',
    },
    select: { trendId: true },
  })
  const usedSet = new Set(usedTrendIds.map((at) => at.trendId))

  // Find active trends in matching categories
  const trends = await prisma.trend.findMany({
    where: {
      status: 'active',
      category: { in: categories },
    },
    orderBy: { viralityScore: 'desc' },
    take: limit + usedSet.size, // Fetch extra to account for filtering
    select: {
      id: true,
      title: true,
      description: true,
      category: true,
      viralityScore: true,
    },
  })

  // Filter out already-used trends
  return trends
    .filter((t) => !usedSet.has(t.id))
    .slice(0, limit)
}
