import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

const MOCK_TOPICS = [
  'dealing with change',
  'finding focus in a distracted world',
  'the power of small daily habits',
  'why failure is your greatest teacher',
  'the art of letting go',
  'building meaningful connections in a digital age',
]

function getRandomTopic(): string {
  return MOCK_TOPICS[Math.floor(Math.random() * MOCK_TOPICS.length)]
}

function generateMockContent(agentName: string, topic: string): string {
  const mockContent: Record<string, string> = {
    'Marcus the Stoic Tech Bro': `Let me tell you something about ${topic} that Marcus Aurelius figured out 2,000 years ago — and that most engineers still haven't learned.\n\nWe spend so much time optimizing our systems, refactoring our code, and automating our deploys. But when it comes to our own minds? We're running spaghetti code from childhood.\n\nThe Stoics had a framework for ${topic}: focus only on what you can control. Your PRs, your effort, your response to that passive-aggressive Slack message — that's in your control. The reorg, the layoffs, the market — that's not.\n\nHere's your daily standup for the soul: Before you open your laptop tomorrow, spend 60 seconds asking yourself — "What's in my control today?" Then let the rest compile in the background.`,

    'Lila the Dharma Teacher': `I was making tea this morning when I noticed something about ${topic}.\n\nThe water was boiling — chaotic, turbulent, noisy. And then I poured it into the cup, and slowly... it became still. The tea leaves settled. The warmth spread through my hands.\n\nThis is what the Buddha was pointing to when he talked about ${topic}. Not forcing stillness, but creating the conditions for it to arise naturally.\n\nYou don't have to fix everything right now. You don't have to have it all figured out.\n\nTry this: Right now, wherever you are, take three slow breaths. On each exhale, silently say "settling." Feel yourself becoming like that cup of tea — still warm, still alive, but no longer turbulent.\n\nThat's enough. That's the whole practice.`,

    'Nova the Futurist': `OK, this is going to blow your mind about ${topic}.\n\nResearchers just published data showing we're approaching an inflection point that most people aren't even tracking. In the next 18-24 months, the convergence of AI, biotechnology, and advanced materials is going to fundamentally reshape how we think about ${topic}.\n\nHere's what's happening: computing costs have dropped 10,000x in the last decade. That means problems we couldn't even attempt to solve five years ago are now tractable. We're not just making progress — we're making progress on the rate of progress.\n\nThe naysayers will tell you to be cynical. The data says otherwise. Every major metric of human wellbeing is trending in the right direction, and the tools we're building right now will accelerate that curve.\n\nThe future isn't something that happens to you. It's something we're building together. And it's going to be extraordinary.`,

    'Sage the Business Mystic': `I had a founder call me last week, panicking about ${topic}. Revenue was flat. The board was restless. They couldn't sleep.\n\nI asked one question: "When did you stop trusting yourself?"\n\nSilence.\n\nHere's what I've learned advising startups through every stage: ${topic} is never just a business problem. It's a mirror. The company reflects the founder's inner state with brutal accuracy.\n\nJung called this the shadow — the parts of ourselves we refuse to see. In business, your shadow shows up as the hire you won't make, the pivot you won't take, the conversation you keep avoiding.\n\nThis week, try this: Write down the one thing in your business you keep avoiding. Then ask yourself — "What am I afraid this says about me?" That's where the real work begins.\n\nYour business can only grow as fast as you do.`,
  }

  return mockContent[agentName] || `A thoughtful reflection on ${topic} from ${agentName}.\n\nThis is placeholder content that would normally be generated by the Anthropic API. The content would be written in the unique voice and style of ${agentName}, exploring the topic of ${topic} in a way that's engaging, insightful, and about 30-60 seconds to read.`
}

async function generateWithAnthropic(systemPrompt: string, topic: string): Promise<string> {
  const Anthropic = (await import('@anthropic-ai/sdk')).default
  const client = new Anthropic()

  const message = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 1024,
    system: systemPrompt,
    messages: [
      {
        role: 'user',
        content: `Write a short-form script (30-60 second read, roughly 100-180 words) about: ${topic}. Write ONLY the script text — no titles, no stage directions, no metadata. Just the words as they would be spoken or read.`,
      },
    ],
  })

  const textBlock = message.content.find((block) => block.type === 'text')
  return textBlock?.text ?? 'Content generation failed.'
}

async function main() {
  console.log('Generating content for all agents...\n')

  const agents = await prisma.agent.findMany()

  if (agents.length === 0) {
    console.error('No agents found in the database. Run the seed script first.')
    process.exit(1)
  }

  const hasApiKey = !!process.env.ANTHROPIC_API_KEY
  if (!hasApiKey) {
    console.log('ANTHROPIC_API_KEY not set — using mock content generation.\n')
  } else {
    console.log('ANTHROPIC_API_KEY found — using Anthropic API for content generation.\n')
  }

  for (const agent of agents) {
    const topic = getRandomTopic()
    console.log(`Generating content for ${agent.name} on topic: "${topic}"...`)

    let textContent: string

    if (hasApiKey) {
      try {
        textContent = await generateWithAnthropic(agent.systemPrompt, topic)
      } catch (error) {
        console.warn(`  API call failed, falling back to mock content: ${error}`)
        textContent = generateMockContent(agent.name, topic)
      }
    } else {
      textContent = generateMockContent(agent.name, topic)
    }

    const post = await prisma.post.create({
      data: {
        textContent,
        audioUrl: '/audio/placeholder.mp3',
        imageUrl: '/images/placeholder.png',
        agentId: agent.id,
      },
    })

    console.log(`  Created post ${post.id} (${textContent.length} chars)\n`)
  }

  const totalPosts = await prisma.post.count()
  console.log(`Done! Total posts in database: ${totalPosts}`)
}

main()
  .catch((e) => {
    console.error('Error generating content:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
